import Head from 'next/head';
import Intro from '../components/Intro/Intro';
import Container from '../layout/Container/Container.component';

const Home = () => {
  return (
    <>
      <Head>
        <title>Charan | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Intro />
      </Container>
    </>
  );
};

export default Home;
